spring:
  application:
    name: FirstSpringApplication

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - mappings
          - health
  info:
    env:
      enabled: true

info:
  app:
    name: FirstSpringApplication
    version: 0.0.1-SNAPSHOT
    description: My first Spring Boot application for learning purposes